version: '3'
services:
  app:
    build:
      context: ./
    volumes:
        - ./:/app:delegated
    # environment:
    #   - "XDEBUG_CONFIG=remote_host=host.docker.internal"
    #   - "DB_PORT=3306"
    #   - "DB_HOST=database"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 3G
